export const OPEN_DRAWER='drawerModal/OPEN_DRAWER'
export const CLOSE_DRAWER='drawerModal/CLOSE_DRAWER'
export const OPEN_FORM_EDIT_PROJECT='drawerModal/OPEN_FORM_EDIT_PROJECT'
export const SET_SUBMIT_EDIT_PROJECT='drawerModal/SET_SUBMIT_EDIT_PROJECT'
export const SET_SUBMIT_CREATE_TASK='drawerModal/SET_SUBMIT_CREATE_TASK'
export const EDIT_PROJECT='drawerModal/EDIT_PROJECT'